version: '3.7'

# Networks
networks:
  # Internal network
  internal:
    driver: bridge

# Services
services:
  # Nginx
  nginx:
    image: webdevops/php-nginx:8.2
    container_name: nginx
    networks:
      - internal
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - PHP_DATE_TIMEZONE=UTC
      - PHP_DISPLAY_ERRORS=0
      - WEB_DOCUMENT_INDEX=index.php
    expose:
      - 9090
    ports:
      - "8080:80"